import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import 'primereact/resources/primereact.min.css';
import 'primeicons/primeicons.css';
import 'primeflex/primeflex.css';
import "primereact/resources/themes/bootstrap4-light-blue/theme.css";
import { PrimeReactProvider, PrimeReactContext } from 'primereact/api';
import Navbar from "@/components/Navbar/Navbar";
import SidePanel from "@/components/SidePanel/SidePanel";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
      <PrimeReactProvider>
      <div className="bg-white h-screen overflow-hidden">
        <Navbar/>
        <div className="flex h-full">
        <SidePanel/>
          {children}
        </div>
      </div>
      </PrimeReactProvider>
    </body>
  </html>
  );
}
